#!/bin/bash

# Define the target directory
workspace_dir="/Users/dorotakopczyk/Workspace"

# Create the directory if it doesn't exist
mkdir -p "$workspace_dir"

# Loop through the list of repositories
while IFS= read -r repo_url
do
    # Extract the repository name from the URL
    repo_name=$(basename "$repo_url" .git)
    
    # Clone the repository to the workspace directory
    git clone "$repo_url" "$workspace_dir/$repo_name"
    
    # Create the entry for the text file
    text_entry="$workspace_dir/$repo_name,$repo_url"
    
    # Append the entry to the text file
    # software_engineering_scripts/bulk_cloner/clone_my_repos.sh
    echo "$text_entry" >> "$workspace_dir/software_engineering_scripts/bulk_cloner/repo_list.txt"
done <<EOL
https://github.com/guavabot/marsh-permissions.git
https://github.com/esoxjem/MovieGuide.git
https://github.com/maniekq/TakeMe.git
https://github.com/RockLobstre/Parrot.git
https://github.com/RailwayStations/RSAndroidApp.git
https://github.com/anitaa1990/TrailersApp.git
https://github.com/reggieray/Random-Quiz.git
https://github.com/halevibarak/SAFE-DNS.git
https://github.com/CriticalMaps/criticalmaps-android.git
https://github.com/leavjenn/Hews.git
https://github.com/murdly/tagop.git
https://github.com/KlubJagiellonski/pola-android.git
https://github.com/dagi12/reval-android.git
https://github.com/Woochang4862/Soon.git
https://github.com/digital-voting-pass/polling-station-app.git
https://github.com/jmalenko/alarm-morning.git
https://github.com/true-that/android.git
https://github.com/veniosg/Dir.git
https://github.com/dobrowol/stylowePlywanie.git
https://github.com/huang840801/Foodie.git
https://github.com/UniversityofWarwick/mywarwick-android.git
https://github.com/caramelool/banco-neon.git
https://github.com/GroopyMusic/GroopyApp.git
https://github.com/TachibanaGeneralLaboratories/download-navi.git
https://github.com/proninyaroslav/libretorrent.git
https://github.com/TeamAmaze/AmazeFileManager.git
https://github.com/KevinJ1008/Fitnessch.git
https://github.com/rubysun137/Split-It.git
https://github.com/ajdf24/AlarmSMSApp.git
https://github.com/malmstein/yahnac.git
https://github.com/ChuChuYu/LifeAPP.git
https://github.com/tutao/tutanota.git
https://github.com/associazione-rousseau/voting-chain-app.git
https://github.com/EvgenyKravtsov/Beacon.git
https://github.com/QuantumLeaper/android-wallet.git
https://github.com/MicGun/LeLeLe.git
https://github.com/bugy/SheLi.git
https://github.com/PraveenSheroes/sheroes-android.git
https://github.com/KChernenko/WhatToWatch.git
https://github.com/dbahat/conventions.git
https://github.com/pekebyte/somosoco.git
https://github.com/DeychAI/cookchooser.git
https://github.com/Infineon/BlockchainSecurity2Go-Android.git
https://github.com/libriciel/i-Parapheur-Android.git
https://github.com/zinfin/NearbyPlaces.git
https://github.com/gentlecat/Simple-Counter.git
https://github.com/wownero/wownerujo.git
https://github.com/niteshpatel/ministocks.git
https://github.com/Swati4star/Images-to-PDF.git
https://github.com/hi77er/mosy.Android.git
https://github.com/phillipao/juryduty.git
https://github.com/SUPLA/supla-android.git
https://github.com/Pozzoooo/JavascriptAutomator.git
https://github.com/Artenes/speedbro.git
https://github.com/Bernie-2016/fieldthebern-android.git
https://github.com/nishaSTM/Logistic-Demo-App.git
https://github.com/hitherejoe/HackerNewsReader.git
https://github.com/kids-cademy/quiz.instruments.git
https://github.com/liamo7/Tally-Android.git
https://github.com/jmodrako/TrainingAppRecipes.git
https://github.com/rainqer/qrgen.git
https://github.com/IkechukwuAKalu/krypto.git
https://github.com/HaojieZheng/BadmintonScoreCounter.git
https://github.com/apachucy/MTGDraftParingApp.git
https://github.com/u-blox/Android-u-blox-BLE.git
https://github.com/andstatus/andstatus.git
https://github.com/receme/SafetyCharger.git
https://github.com/abhijitvalluri/fitnotifications.git
https://github.com/romanchekashov/currency-and-stock-widget.git
https://github.com/BarryBryant/rally-genius-android.git
https://github.com/jonatantierno/huggingNepal.git
https://github.com/danielmroczka/auto-tethering.git
https://github.com/WojciechKo/stack-overflow-android.git
https://github.com/greenhub-project/batteryhub.git
https://github.com/zoromatic/ZoromaticWidgets.git
https://github.com/Potass/ConnectBot.git
https://github.com/mikeschen/HangBoardRepeatersAndroid.git
https://github.com/ashdavies/eternity.git
https://github.com/apps4av/avare.git
https://github.com/connectbot/connectbot.git
https://github.com/YoeriNijs/NoteBuddy.git
https://github.com/cotechde/termbot.git
https://github.com/thuryn/your-local-weather.git
https://github.com/zlodag/aRMOur.git
https://github.com/andstatus/todoagenda.git
https://github.com/mathisdt/sdbviewer.git
https://github.com/drymarev/rxbsuir.git
https://github.com/KeltApps/Missgsanchez.git
https://github.com/farmasek/Audio_Manager.git
https://github.com/michael830713/ProjectBoxScore.git
https://github.com/steveholt55/Football-College-Trivia-Android.git
https://github.com/chaimt/JewishDay.git
https://github.com/Purdue-ACM-SIGApp/PurdueLaundry-android.git
https://github.com/Psycadelik/anotherone.git
https://github.com/joenelsong/android_IntervalTimerMetronome.git
https://github.com/rmm01/CycleBattleDemo.git
https://github.com/rene-anderes/CookbookApp.git
https://github.com/ashomokdev/OCRme.git
https://github.com/pjwelcome/WeatherAppDemo.git
https://github.com/guliash/Calculator.git
https://github.com/Ryanair/android-layered-architecture-example.git
https://github.com/d-Rickyy-b/MGGVertretungsplan.git
https://github.com/dshalom/MovieMania.git
https://github.com/jamie084/DPW.git
https://github.com/tahnok/ALRM.git
https://github.com/davidshen84/ResetWiFi.git
https://github.com/Tenacle/FifthElement.git
https://github.com/nextcloud/news-android.git
https://github.com/chrisboyle/sgtpuzzles.git
https://github.com/fasteque/rgb-tool.git
https://github.com/richsmith/sexytopo.git
https://github.com/koelleChristian/trickytripper.git
https://github.com/lexica/lexica.git
https://github.com/ccrama/Slide.git
https://github.com/dsolonenko/financisto.git
https://github.com/etp404/frenchverbinator.git
https://github.com/xxxcucus/planes.git
https://github.com/Dev1012You/GGP_Android.git
https://github.com/thomasfischersm/BagZombie.git
https://github.com/darkowlzz/gmsapp.git
https://github.com/nkarasch/RepeatingReminder.git
https://github.com/brentn/TomatoHub.git
https://github.com/varunrpillai/karma_android.git
https://github.com/mendhak/gpsmapper.git
https://github.com/Kuan-Hsien/TimeManagement.git
https://github.com/Klemek/AngersTramWidget.git
https://github.com/RogerTsai917/MakeCoffe.git
https://github.com/lewismcgeary/AndroidGameofLife.git
https://github.com/dminor/mockingbird.git
https://github.com/damdordev/notepad.git
https://github.com/gstraube/cythara.git
https://github.com/wizmer/syncorg.git
https://github.com/luankevinferreira/expenses.git
https://github.com/rapidpro/surveyor.git
https://github.com/SvenWerlen/pathfinderfr-android.git
https://github.com/thomasfischersm/PeerToPeerOxygen.git
https://github.com/Aedge90/Nine-Mens-Morris-Android.git
https://github.com/mlintonford/bikecloud.git
https://github.com/sky-map-team/stardroid.git
https://github.com/lsaccoz/Beacon.git
https://github.com/federicoiosue/Omni-Notes.git
https://github.com/maxpower47/PinDroid.git
https://github.com/MarcusWolschon/osmeditor4android.git
https://github.com/codinguser/gnucash-android.git
https://github.com/brarcher/rental-calc.git
https://github.com/manismagic/HackerNews.git
https://github.com/niccokunzmann/mundraub-android.git
https://github.com/bparmentier/WiFiKeyShare.git
https://github.com/RyuzakiKK/NoteCrypt.git
https://github.com/namlit/siteswap_generator.git
https://github.com/SecUSo/privacy-friendly-shopping-list.git
https://github.com/gsantner/markor.git
https://github.com/vbier/habpanelviewer.git
https://github.com/brarcher/loyalty-card-locker.git
https://github.com/lesspass/lesspass.git
https://github.com/ramack/ActivityDiary.git
https://github.com/kalaspuffar/secure-quick-reliable-login.git
https://github.com/Berlin-Vegan/berlin-vegan-guide.git
https://github.com/cfatihb/buluterp.git
https://github.com/nettrash/SIB.Android.git
https://github.com/mick88/dit-timetables.git
https://github.com/amrendra18/codezera.git
https://github.com/SecUSo/privacy-friendly-battleship.git
https://github.com/bigmikehoncho/RiskDiceSimulator.git
https://github.com/PiXeL16/Sea-Nec-IO.git
https://github.com/eastlighting1/producejakj.git
https://github.com/TimLavers/IndoFlashJava.git
https://github.com/Jindetta/Android-Sudoku.git
https://github.com/DanielTheDeveloper/My-Digital-Safe.git
https://github.com/Mools222/Consentcoin.git
https://github.com/fedeLizondo/BaseDeDatos.git
https://github.com/ProjectUNBI/Iyek_Retouch.git
https://github.com/flakeynetworks/QRSequencer-Android.git
https://github.com/MahalingamD/ROTO.git
https://github.com/psocha/GoGameClock.git
https://github.com/sysrqb/ortt.git
https://github.com/kikAutomation/3d.git
https://github.com/Evin1-/PopularMovies.git
https://github.com/artem122ya/TomatoTimer-Android.git
https://github.com/mach91uk/alarmatic.git
https://github.com/jay1729/Class-Manager.git
https://github.com/jamsinclair/ow-camera-android.git
https://github.com/sullivankw/blackjack-v2-android-app.git
https://github.com/figonzal1/LastQuakeChile.git
https://github.com/abahnj/Confession.git
https://github.com/rahobbs/ToDoList.git
https://github.com/CarstenKarbach/VoBox.git
https://github.com/patrickma345/Shopper.git
https://github.com/MrR0bo7/FreezerManager.git
https://github.com/jeremybrooks/readsy-android.git
https://github.com/sirconceptz/MyPantry.git
https://github.com/nsnikhil/RandomNo.git
https://github.com/GiPiLab/simulateur-de-placements.git
https://github.com/savvavolobuev/NoOpinion.git
https://github.com/konifar/droidkaigi2016.git
https://github.com/brcamp13/lostInTheWoods.git
https://github.com/ASofterSpace/UniversalConverter.git
https://github.com/jaunerc/ThinkQuick.git
https://github.com/Digolodollarz/HolyBible.git
https://github.com/Fewlaps/flone-android.git
https://github.com/ezet/movie-tracker.git
https://github.com/5calls/android.git
https://github.com/yuragr/BPolite.git
https://github.com/1andyn/droid_sch.git
https://github.com/OpenSeizureDetector/Android_Pebble_SD.git
https://github.com/karlkar/queuedroid.git
https://github.com/jamie23/Android-Wallpaper-Manager.git
https://github.com/PlantandFoodResearch/aspire-lite.git
https://github.com/vexelon-dot-net/currencybg.app.git
https://github.com/lizyeseul/SoftHanJolUp.git
https://github.com/peppermintcom/Peppermint-Android.git
https://github.com/CarlosAguA/traccar-manager-android.git
https://github.com/codimoc/PrismaCallBlocker.git
https://github.com/dmayboroda/friendinneed.git
https://github.com/salminnella/PreScoop.git
https://github.com/brianjaustin/permitlog-android.git
https://github.com/sewerina/reek.git
https://github.com/AndrewPochapsky/RoutinePlanner.git
https://github.com/michaeljordanr/JacocoCoverageModel.git
https://github.com/FrankSpitulski/TritonTrade.git
https://github.com/MatthewDailey/ruthless-priorities-android.git
https://github.com/ucam-emule/eMule.git
https://github.com/egross91/CIS4914.git
https://github.com/Marrrrtthias/Zeiterfassung.git
https://github.com/KleberDevMen/AcampamentoAdventista.git
https://github.com/aksel/steganography-app.git
https://github.com/ciuc/InternetRadioClock.git
https://github.com/cjndubisi/Pro-Tracker-Android.git
https://github.com/BeedleEiEi/final_project_android.git
https://github.com/TekkLabs/memoria-politica.git
https://github.com/Scaronthesky/UK-Gebaerden_Muensterland.git
https://github.com/UlricusR/FPU_Calculator.git
https://github.com/sowd/TagCam.git
https://github.com/jangerhard/BitcoinWalletTracker.git
https://github.com/plukic/ZavrsniRad-Mobile.git
https://github.com/charlesmadere/that-lil-hummingbird.git
https://github.com/SecUSo/privacy-friendly-food-tracker.git
https://github.com/BYUCS240TA/SuperAsteroidsStartingCode.git
https://github.com/VolcanicSlippers/sugarcontrol.git
https://github.com/IgorGee/MTA-Perfect-Fare.git
https://github.com/GoneUp/Htwg_LsfPlan.git
https://github.com/longdivision/hex.git
https://github.com/nordfalk/AndroidElementer.git
https://github.com/adrmal/DrSmartMobile.git
https://github.com/linux-colonel/AdminControl.git
https://github.com/ivydrenkov/HookahLocator.git
https://github.com/JobardJerome14/KenkenJJ.git
https://github.com/Jigsaw-Code/Intra.git
https://github.com/NikShuvalov/Twas.git
https://github.com/astrada/smartwishlistapp-android.git
https://github.com/rijogeorge7/TipCalculator.git
https://github.com/Tiraza/YGOPS.git
https://github.com/WesBunton/MyCertificates.git
https://github.com/The224/Infectious_Mobile.git
https://github.com/giorgiosironi/fizz-buzz-android.git
https://github.com/rstockbridge/ShowStats.git
https://github.com/luni66/Arpav.git
https://github.com/marcosdiez/LimiteCartao.git
https://github.com/Jenova7/Electra-Android.git
https://github.com/karino2/MeatPieDay.git
https://github.com/OmarMohamedDev/CentralTrackingWay.git
https://github.com/YonahKarp/SeatSuite.git
https://github.com/mkloar/DrinkMoreWater.git
https://github.com/carcme/btown_mvp.git
https://github.com/RCasatta/EternityWallAndroid.git
https://github.com/ineiti/Dictionary2.git
https://github.com/doomcatLee/translate-sms-android.git
https://github.com/Fitzbattleaxe/DNi.git
https://github.com/gfx/Android-Helium.git
https://github.com/tomszilagyi/svhu1972.git
https://github.com/maneca/ProgramGenerator.git
https://github.com/gatzka/android-scan.git
https://github.com/Ashish-Bansal/OneTapVideoDownload.git
https://github.com/aayaffe/SailingRaceCourseManager.git
https://github.com/JavonDavis/Resume-Android-App.git
https://github.com/SmileChaoLee/BouncyBall.git
https://github.com/Izodine/Capstone-Project.git
https://github.com/evolv34/p2j-v2.git
https://github.com/hodlwallet/hodl-wallet-android.git
https://github.com/borfast/arrispwgen-android.git
https://github.com/Tuchnyak/smart-criteria.git
https://github.com/shiftlyapp/Shiftly.git
https://github.com/sfeto/nongli.git
https://github.com/hei-connect/android.git
https://github.com/jrodalo/copit.git
https://github.com/sirrom2005/StingaLtd.git
https://github.com/sicheng-zhu/HouseholdManagement.git
https://github.com/meyerd/funktrainer.git
https://github.com/Johnsi1994/Bid-Sneakers.git
https://github.com/Mools222/HOEK-Helper-v1.git
https://github.com/IntegerCompany/HzCalculator.git
https://github.com/pumpkinz/pumpkin-reader.git
https://github.com/divizdev/WallpaperGallery.git
https://github.com/hasgeek/android.git
https://github.com/martincheung/wrestlejam.git
https://github.com/hapramp/1Rramp-Android.git
https://github.com/maciej-kaznowski/Londair.git
https://github.com/leonardost/kifu-recorder.git
https://github.com/droidconpl/droidcon-2015-mobile-app.git
https://github.com/eReuse/android-old.git
https://github.com/Enathen/AllergyTest.git
https://github.com/JoffreyLGT/MySteamGames.git
https://github.com/fafeichter/Runnergy.git
https://github.com/magenta-aps/VoKS-android.git
https://github.com/filippella/Best-Amharic-Keyboard.git
https://github.com/steevp/YoureWinnerApp.git
https://github.com/peterhuangSC/Jugmaster.git
https://github.com/ArnaudPiroelle/marvel-muzei-android.git
https://github.com/gummangummangumman/WhoseTweetIsThatAppThing.git
https://github.com/AndyCooler/github-pass15.git
https://github.com/NoiceAppOrg/noice-android.git
https://github.com/memoeslink/Adivinador.git
https://github.com/ROSHiix/ravencoin-android.git
https://github.com/medic/medic-android.git
https://github.com/nextcashtech/android_wallet.git
https://github.com/JakeEsveldDevelopment/Vape-Bible-Juice-Calc.git
https://github.com/chervonyi/board-game-android.git
https://github.com/MissMormie/CWO-Training-App.git
https://github.com/FLF69740/FMEIManager.git
https://github.com/Fire3galaxy/SilverLining.git
https://github.com/zhumayun/Fallout-4-Terminal-Solver.git
https://github.com/forestcoinspace/WavesWallet-android.git
https://github.com/ryan-mcgoff/assignment4.git
https://github.com/ranmocy/MonkeyTree.git
https://github.com/stv2pointo/SmartMeds.git
https://github.com/StefanPahlplatz/proximity-map.git
https://github.com/arcbit/arcbit-android.git
https://github.com/juanmadelboca/spitball-android.git
https://github.com/elafargue/opencamera-ble.git
https://github.com/Rlshep/BJCPBeerStyles_Android.git
https://github.com/daaron4/HeartsAndroid.git
https://github.com/yasmindunsky/FrizzleApp.git
https://github.com/JPMoresmau/JPWorkoutLog.git
https://github.com/maxfie1d/SpinnerMeijin.git
https://github.com/TheMacWeekly/Android.git
https://github.com/svenmeier/coxswain.git
https://github.com/gonzalo-m/ohms-law.git
https://github.com/AndyRadionov/15Puzzle.git
https://github.com/tobyli/Sugilite_development.git
https://github.com/luke-c/Ikue.git
https://github.com/slt-programmers/macrologAndroid.git
https://github.com/akgoal/YourTurnTimer.git
https://github.com/jooejooe/tigase-mobilemessenger.git
https://github.com/theblackwidower/KanaQuiz.git
https://github.com/artemkv/notedok-android-app.git
https://github.com/doofmars/GHB-Traffic.git
https://github.com/sebastianhaeni/edgewars.git
https://github.com/smirnov-i-SPbAU/BrainRing.git
https://github.com/grishmashrestha/ekaai.git
https://github.com/AJWurts/AndroidSolitaire.git
https://github.com/medhelp-app/android.git
https://github.com/pinpinbox/app.git
https://github.com/tkrajina/10000sentences.git
https://github.com/mneidhardt/MinAppNr1.git
https://github.com/fdoclaves/BGGQuery.git
https://github.com/Myced/pcc.git
https://github.com/mdilaveroglu/Quoter-Android.git
https://github.com/ahn94/DrywallTally.git
https://github.com/wilmol/Sleep-Easy.git
https://github.com/EightBitBoy/hijacr.git
https://github.com/Ifsttar/NoiseCapture.git
https://github.com/biodunduke/BookMeUp-Backend.git
https://github.com/mrvivacious/PorNo_Android.git
https://github.com/ilario-pierbattista/wescape-android.git
https://github.com/w32blaster/helsinki-timetables.git
https://github.com/infostretch-cd/expense-tracker.git
https://github.com/ChernyshovYuriy/OpenRadio.git
https://github.com/izacus/Parkomat.git
https://github.com/emitchel/uDraw.git
https://github.com/GlobalTechnology/android-ekko.git
https://github.com/arvipDev/EnergyConversionLabDemo.git
https://github.com/amarradi/bloginfo.git
https://github.com/altamish1994/frisbee-se2.git
https://github.com/playerone-id/EosCommander.git
https://github.com/cyblack/HelpMom.git
https://github.com/andynaguyen/Kisetsu.git
https://github.com/frodegill/GridWalking.git
https://github.com/sickmartian/QuickReminderWidget.git
https://github.com/sachinjha-softuvo/mobile-facny-new.git
https://github.com/kuwako/TodoKuwako.git
https://github.com/n8yn8/ABMA-Android.git
https://github.com/mrzzy/Skeem.git
https://github.com/dparker1005/app_JustChess.git
https://github.com/LazzyBee/LazyBee-Android.git
https://github.com/darekbx/sugar.git
https://github.com/gpadmaku1/card-reader.git
https://github.com/fantazac/TP3Mobile2.git
https://github.com/incwo/erp-android.git
https://github.com/Krock21rus/MafiaGame.git
https://github.com/josdem/jugoterapia-mobile.git
https://github.com/Primo17/EliteanimesApp.git
https://github.com/KAPLANDROID/Game-Of-Life.git
https://github.com/OakOnEll/DnDCharacter.git
https://github.com/christopherkade/Task-Forge.git
https://github.com/uozuAho/YakBox.git
https://github.com/EthamQ/CustomNewsAndroid_2019.git
https://github.com/Nikoloutsos/myHomework.git
https://github.com/tuxmobil/CampFahrplan.git
https://github.com/netmackan/ATimeTracker.git
https://github.com/beemdevelopment/Aegis.git
https://github.com/mschlauch/comfortreader.git
https://github.com/buggins/coolreader.git
https://github.com/domogik/domodroid.git
https://github.com/mannd/epmobile.git
https://github.com/clemensbartz/essential-launcher.git
https://github.com/bilde2910/Hauk.git
https://github.com/xbmc/Kore.git
https://github.com/SyncedSynapse/Kore.git
https://github.com/Adonai/Man-Man.git
https://github.com/httpdispatch/MissedNotificationsReminder.git
https://github.com/WangDaYeeeeee/Mysplash.git
https://github.com/stefan-niedermann/nextcloud-notes.git
https://github.com/AnaelMobilia/NextINpact-Unofficial.git
https://github.com/slapperwan/gh4a.git
https://github.com/dmfs/opentasks.git
https://github.com/ValleZ/Paper-Wallet.git
https://github.com/tengel/AndroidPlanisphere.git
https://github.com/oe1rfc/CampFahrplan.git
https://github.com/QuickLyric/QuickLyric.git
https://github.com/geecko86/QuickLyric.git
https://github.com/QuantumBadger/RedReader.git
https://github.com/haiwen/seadroid.git
https://github.com/termux/termux-app.git
https://github.com/lordi/tickmate.git
https://github.com/traccar/traccar-client-android.git
https://github.com/mathisdt/trackworktime.git
https://github.com/andreynovikov/trekarta.git
https://github.com/gelin/weather-notification.git
https://github.com/wiglenet/wigle-wifi-wardriving.git
https://github.com/wikimedia/apps-android-commons.git
https://github.com/redsolution/xabber-android.git
EOL
